apiVersion: v1
kind: Service
metadata:
  name: otel-collector-gateway-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: otel-collector-gateway-collector
    app.kubernetes.io/managed-by: opentelemetry-operator
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
